

export interface JournalMetadata {
  id: string;
  filename: string;
  title: string;
  uploader: string;
  detectedAuthor: string;
  authorInstitution: string;
  publicationYear: string | null;
  journalSource: string;
  doi: string | null;
  pdfUrl: string;
  uploadDate: string;
  status: 'pending' | 'approved' | 'rejected';
  fileSize: string;
  contentPreview?: string;
}

export const extractedMetadata: JournalMetadata[] = [
  {
    "id": "journal-d9ef73181d87",
    "filename": "1-s2.0-S2950264024000078-main.pdf",
    "title": "1-s2.0-S2950264024000078-main",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Solomon Evro, Abdurahman Ajumobi , Darrell Mayon , Olusegun",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/1-s2.0-S2950264024000078-main.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "5.61 MB",
    "contentPreview": "Navigating battery choices: A comparative study of lithium iron phosphate \nand nickel manganese cobalt battery technologies\nSolomon Evro*, Abdurahman Ajumobi , Darrell Mayon , Olusegun Stanley Tomomewo*\nDepartment of Energy Engineering, College of Engineering and Mines, University of North Dakota, Grand Forks 58203, ND, United States\nARTICLE INFO\nKeywords:\nLFP batteries\nNMC batteries\nBattery comparisons\nAdvanced energy storage\nBattery safety\nEnvironmental impact of batteries\nBattery market trend"
  },
  {
    "id": "journal-26db6dce4793",
    "filename": "1872099998_0.pdf",
    "title": "1872099998_0",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Renewable energy mix enhancement : the power of et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2023",
    "journalSource": "Unknown",
    "doi": "10.32479/ijeep.14796.",
    "pdfUrl": "./data_jurnal/1872099998_0.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.74 MB",
    "contentPreview": "Agustina, Ika; Khuan, Hendri; Aditi, Bunga et al.\nArticle\nRenewable energy mix enhancement : the power of\nforeign investment and green policies\nInternational Journal of Energy Economics and Policy\nProvided in Cooperation with:\nInternational Journal of Energy Economics and Policy (IJEEP)\nReference: Agustina, Ika/Khuan, Hendri et. al. (2023). Renewable energy mix enhancement : the\npower of foreign investment and green policies. In: International Journal of Energy Economics and\nPolicy 13 (6), S. 37"
  },
  {
    "id": "journal-34bfbbeb16a0",
    "filename": "1899283420_0.pdf",
    "title": "1899283420_0",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Carbon neutrality and sustainable development : et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": "10.32479/ijeep.15953.",
    "pdfUrl": "./data_jurnal/1899283420_0.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.44 MB",
    "contentPreview": "Saudi, Nur Dwiana Sari; Reviane, Indraswati Tri Abdi; Paddu, Abdul Hamid et al.\nArticle\nCarbon neutrality and sustainable development :\nan empirical study of Indonesia's renewable energy\nadoption\nInternational Journal of Energy Economics and Policy\nProvided in Cooperation with:\nInternational Journal of Energy Economics and Policy (IJEEP)\nReference: Saudi, Nur Dwiana Sari/Reviane, Indraswati Tri Abdi et. al. (2024). Carbon neutrality\nand sustainable development : an empirical study of Indonesia's"
  },
  {
    "id": "journal-29dcf03b78a9",
    "filename": "1iuc2if-Tritto_Indonesia_Nickel.pdf",
    "title": "1iuc2if-Tritto_Indonesia_Nickel",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "How Indonesia Used Chinese et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2023",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/1iuc2if-Tritto_Indonesia_Nickel.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.32 MB",
    "contentPreview": "CARNEGIE ENDOWMENT FOR INTERNATIONAL PEACE  |   i\nHow Indonesia Used Chinese \nIndustrial Investments to Turn \nNickel into the New Gold  \nAngela TrittoAPRIL 2023\n"
  },
  {
    "id": "journal-1465330cd618",
    "filename": "331481521009.pdf",
    "title": "331481521009",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Artificial Intelligence and chatbots for sustainable higher",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/331481521009.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.35 MB",
    "contentPreview": "Estudios e Investigaciones\nArtificial Intelligence and chatbots for sustainable higher education: a systematic \nreview\nInteligencia Artificial y chatbots para una educación superior sostenible: una revisión sistemática\nEva Jiménez- García\nUniversidad Europea de Madrid, UEM , España\n https:// orcid.org/ 0000-0001-6541-3517\nJudit Ruiz- Lázaro\nUniversidad Nacional de Educación a Distancia, UNED , \nEspaña\n https:// orcid.org/ 0000-0003-2036-0428\nSonia Martínez- Requejo\nUniversidad Europea de Madrid,"
  },
  {
    "id": "journal-e9ef097d5bc2",
    "filename": "378-1121-1-PB (1).pdf",
    "title": "378-1121-1-PB (1)",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "NICKEL BAN AND INDONESIA'S DEFENSE: A WTO DISPUTE WITH",
    "authorInstitution": "Not specified",
    "publicationYear": "2023",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/378-1121-1-PB (1).pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.51 MB",
    "contentPreview": " Journal of International Trade, Logistics and Law, Vol. 9, Num. 2, 2023, 1-9 \n \n1 \n \n \nNICKEL BAN AND INDONESIA'S DEFENSE: A WTO DISPUTE WITH \nIMPLICATIONS FOR NATIONAL SECURITY  \n \nReinpal FALEFI  \nThe Republic of Indonesia Defense University  \n \nHikmat Zakky ALMUBARAQ  \nThe Republic of Indonesia Defense University  \n \nNora LELYANA  \nThe Republic of Indonesia Defense University  \n \n \nReceived:  May 22, 2023         Accepted:  Aug 07, 2023            Published:  Dec 01, 2023 \n \nAbstract : \nThe "
  },
  {
    "id": "journal-633366f3daff",
    "filename": "378-1121-1-PB.pdf",
    "title": "378-1121-1-PB",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "NICKEL BAN AND INDONESIA'S DEFENSE: A WTO DISPUTE WITH",
    "authorInstitution": "Not specified",
    "publicationYear": "2023",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/378-1121-1-PB.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.51 MB",
    "contentPreview": " Journal of International Trade, Logistics and Law, Vol. 9, Num. 2, 2023, 1-9 \n \n1 \n \n \nNICKEL BAN AND INDONESIA'S DEFENSE: A WTO DISPUTE WITH \nIMPLICATIONS FOR NATIONAL SECURITY  \n \nReinpal FALEFI  \nThe Republic of Indonesia Defense University  \n \nHikmat Zakky ALMUBARAQ  \nThe Republic of Indonesia Defense University  \n \nNora LELYANA  \nThe Republic of Indonesia Defense University  \n \n \nReceived:  May 22, 2023         Accepted:  Aug 07, 2023            Published:  Dec 01, 2023 \n \nAbstract : \nThe "
  },
  {
    "id": "journal-072d53ee8648",
    "filename": "4757-Article Text-19438-1-10-20250619.pdf",
    "title": "4757-Article Text-19438-1-10-20250619",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Accredited Sinta based on SK. No. /E/KPT/ et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/4757-Article Text-19438-1-10-20250619.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.23 MB",
    "contentPreview": "Journal Scientific of Mandalika (jsm) e -ISSN: 2745 -5955, p -ISSN: 2809 -0543, Vol 6, No 9, 2025  \nwebsite: http://ojs.cahayamandalika.com/index.php/jomla   \nAccredited Sinta 5 based on SK. No. 177/E/KPT/2024  \n \n \n                     This is an open -access article under the CC-BY-SA License.  License.Copyright2024@author (s )     3610 \n \n \nHilirisasi Mineral Pengelolaan Nikel di Indonesia:  \nRegulasi serta Dampak Implementasinya Pada Ekonomi dan Pembangunan \nSmelter  \n \nSyamsul Hidayat  1 \n1"
  },
  {
    "id": "journal-62e92f2a9a6d",
    "filename": "847-PB-1 (1).pdf",
    "title": "847-PB-1 (1)",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "P-ISSN: - E-ISSN: - et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/847-PB-1 (1).pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.19 MB",
    "contentPreview": "Vol.\t12(3):\t549-579,\tSeptember\t2024\t\tDOI:\thttps://doi.org/10.23960/jsl.v12i3.847\t\t\tJurnal\tSylva\tLestari\tJournal\thomepage:\thttps://sylvalestari.fp.unila.ac.id\t  \n 549 P-ISSN: 2339-0913 E-ISSN: 2549-5747 \nReview Article The Impact of Increasing Nickel Production on Forest and Environment in Indonesia: A Review  Miftahul Jannah Nasution1,2*, Tugiyono2, Samsul Bakri2, Agus Setiawan2, Murhadi2, Christine Wulandari2, Endro Prasetyo Wahono2 1 Regional Research and Development Agency, Lampung Province, "
  },
  {
    "id": "journal-7625d64bd05e",
    "filename": "847-PB-1.pdf",
    "title": "847-PB-1",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "P-ISSN: - E-ISSN: - et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/847-PB-1.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.19 MB",
    "contentPreview": "Vol.\t12(3):\t549-579,\tSeptember\t2024\t\tDOI:\thttps://doi.org/10.23960/jsl.v12i3.847\t\t\tJurnal\tSylva\tLestari\tJournal\thomepage:\thttps://sylvalestari.fp.unila.ac.id\t  \n 549 P-ISSN: 2339-0913 E-ISSN: 2549-5747 \nReview Article The Impact of Increasing Nickel Production on Forest and Environment in Indonesia: A Review  Miftahul Jannah Nasution1,2*, Tugiyono2, Samsul Bakri2, Agus Setiawan2, Murhadi2, Christine Wulandari2, Endro Prasetyo Wahono2 1 Regional Research and Development Agency, Lampung Province, "
  },
  {
    "id": "journal-8e7d6bc4fa8b",
    "filename": "9_101-116_UPEJ+Aditya+Samastha.pdf",
    "title": "9_101-116_UPEJ+Aditya+Samastha",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Terakreditasi SINTA et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/9_101-116_UPEJ+Aditya+Samastha.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.34 MB",
    "contentPreview": " \n \n \n \n  \nUnnes Physics Education Journal  \nTerakreditasi SINTA 3  \nhttps://journal.unnes.ac.id/journals/upej   \nPengembangan Media Pembelajaran Terintegrasi Artificial intelligence  Natural language \nprocessing  Berbasis Mobile  dengan Framework  Flutter pada Materi Energi Terbarukan  \nAditya Samastha, Sunyoto Eko Nugroho  \nJurusan Fisika, Fakultas Matematika dan Ilmu Pengetahuan Alam, Universitas Negeri Semarang , Indonesia  \nGedung D7 Lt. 2, Kampus Sekaran Gunungpati, Semarang 50229  \nInfo "
  },
  {
    "id": "journal-fcb0cb17b1fe",
    "filename": "a795c7a2-5d9d-47bb-9876-dcfa6222a82d (1) - Copy.pdf",
    "title": "a795c7a2-5d9d-47bb-9876-dcfa6222a82d (1) - Copy",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Indonesia ’s Nick el Downstr eaming in the Geopolitics",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/a795c7a2-5d9d-47bb-9876-dcfa6222a82d (1) - Copy.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "3.02 MB",
    "contentPreview": "Page 1/31\nIndonesia ’s Nick el Downstr eaming in the Geopolitics\nof the Global EV Batter y Industr y: A P olitical E conomy\nand Scenario Modeling Analysis\nSyamsul Bachri Soamole \nHaluoleo Univ ersity\nResear ch Ar ticle\nKeywor ds: nick el downstr eaming, industrial policy , causal eff ects, str ategic dependence, global v alue chains,\nener gy geopolitics\nPosted Date:  September 24th, 2025\nDOI: https:/ /doi.or g/10.21203/rs.3.rs-7600869/v1\nLicense:    This work is licensed under a Cr eativ e Com"
  },
  {
    "id": "journal-e056c281fc67",
    "filename": "a795c7a2-5d9d-47bb-9876-dcfa6222a82d (1).pdf",
    "title": "a795c7a2-5d9d-47bb-9876-dcfa6222a82d (1)",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Indonesia ’s Nick el Downstr eaming in the Geopolitics",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/a795c7a2-5d9d-47bb-9876-dcfa6222a82d (1).pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "3.02 MB",
    "contentPreview": "Page 1/31\nIndonesia ’s Nick el Downstr eaming in the Geopolitics\nof the Global EV Batter y Industr y: A P olitical E conomy\nand Scenario Modeling Analysis\nSyamsul Bachri Soamole \nHaluoleo Univ ersity\nResear ch Ar ticle\nKeywor ds: nick el downstr eaming, industrial policy , causal eff ects, str ategic dependence, global v alue chains,\nener gy geopolitics\nPosted Date:  September 24th, 2025\nDOI: https:/ /doi.or g/10.21203/rs.3.rs-7600869/v1\nLicense:    This work is licensed under a Cr eativ e Com"
  },
  {
    "id": "journal-29008fa7bfa8",
    "filename": "a795c7a2-5d9d-47bb-9876-dcfa6222a82d.pdf",
    "title": "a795c7a2-5d9d-47bb-9876-dcfa6222a82d",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Indonesia ’s Nick el Downstr eaming in the Geopolitics",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/a795c7a2-5d9d-47bb-9876-dcfa6222a82d.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "3.02 MB",
    "contentPreview": "Page 1/31\nIndonesia ’s Nick el Downstr eaming in the Geopolitics\nof the Global EV Batter y Industr y: A P olitical E conomy\nand Scenario Modeling Analysis\nSyamsul Bachri Soamole \nHaluoleo Univ ersity\nResear ch Ar ticle\nKeywor ds: nick el downstr eaming, industrial policy , causal eff ects, str ategic dependence, global v alue chains,\nener gy geopolitics\nPosted Date:  September 24th, 2025\nDOI: https:/ /doi.or g/10.21203/rs.3.rs-7600869/v1\nLicense:    This work is licensed under a Cr eativ e Com"
  },
  {
    "id": "journal-80470c0e4157",
    "filename": "Artificial_Intelligence_Chatbot_Platform.pdf",
    "title": "Artificial_Intelligence_Chatbot_Platform",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Email: et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": "10.18178/ijiet.2024.14.1.2021Manuscript",
    "pdfUrl": "./data_jurnal/Artificial_Intelligence_Chatbot_Platform.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.56 MB",
    "contentPreview": "  \nArtificial Intelligence Chatbot Platform: AI Chatbot Platform \nfor Educational Recommendations in Higher Education \nThanarat Kingchang1, Pinanta Chatwattana2,*, and Panita Wannapiroon2 \n1Railway Technical School, Bangkok, Thailand \n2King Mongkut ’s University of Technology North Bangkok, Bangkok, Thailand \nEmail: dew_thanarat@hotmail.com (T.K.); pinanta.c@cit.kmutnb.ac.th (P .C.); panita.w@fte.kmutnb.ac.th (P.W.) \n*Corresponding author \n  \n \nAbstract —AI chatbots platform for educational \nrec"
  },
  {
    "id": "journal-f0327dd8a453",
    "filename": "battery-2030-resilient-sustainable-and-circular.pdf",
    "title": "battery-2030-resilient-sustainable-and-circular",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Battery demand is growing—and so is the need for et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/battery-2030-resilient-sustainable-and-circular.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.48 MB",
    "contentPreview": "Battery 2030: Resilient, sustainable, \nand circular\nBattery demand is growing—and so is the need for \nbetter solutions along the value chain.\nThis article is a collaborative effort by McKinsey in cooperation with the Global Battery Alliance and its members. The authors include \nJakob Fleischmann, Mikael Hanicke, Evan Horetsky, Dina Ibrahim, Sören Jautelat, Martin Linder, Patrick Schaufuss, Lukas Torscht, and \nAlexandre van de Rijt.\n"
  },
  {
    "id": "journal-6192d2b4be7d",
    "filename": "c4ed96219b287181eb962602010754ff793a.pdf",
    "title": "c4ed96219b287181eb962602010754ff793a",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Heinrich Rakuasa, Philia Christi Latue et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": "10.59525/rechtsvinding.v2i2.410",
    "pdfUrl": "./data_jurnal/c4ed96219b287181eb962602010754ff793a.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.38 MB",
    "contentPreview": "RECHTSVINDING  \nVol. 2, 2 (December , 2024), pp. 45-52 \nEISSN: 2987 -4424, DOI: 10.59525/rechtsvinding.v2i2.410  \n  https://journal.civiliza.org/index.php/rechtsvinding  Legal Studies on the Use of Renewable Energy in Environmental \nManagement in Indonesia: A Literature Study  \nHeinrich Rakuasa1, Philia Christi Latue2 \n1 National Research Tomsk State University, Russian Federation; heinrich.rakuasa@yandex.ru   \n2 Universitas Pattimura, Indonesia; philiachristilatue@gmail.com   \n \nARTICLE INFO   "
  },
  {
    "id": "journal-8723e9b75d1a",
    "filename": "Chatbot-for-Education-System.pdf",
    "title": "Chatbot-for-Education-System",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Chatbot for Education System et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2020",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/Chatbot-for-Education-System.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.47 MB",
    "contentPreview": "See discussions, st ats, and author pr ofiles f or this public ation at : https://www .researchgate.ne t/public ation/347902940\nChatbot for Education System\nArticle  · Dec ember 2020\nCITATIONS\n104READS\n25,477\n2 author s, including:\nDr. K S W agh\nSavitrib ai Phule Pune Univ ersity\n46 PUBLICA TIONS    284 CITATIONS    \nSEE PROFILE\nAll c ontent f ollo wing this p age was uplo aded b y Dr. K S W agh  on 25 Dec ember 2020.\nThe user has r equest ed enhanc ement of the do wnlo aded file."
  },
  {
    "id": "journal-437ea7834fda",
    "filename": "Dampak_Ekspansi_Biomassa_sebagai_Energi.pdf",
    "title": "Dampak_Ekspansi_Biomassa_sebagai_Energi",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Dampak Ekspansi Biomassa s ebagai Ener gi Terbar ukan:",
    "authorInstitution": "Not specified",
    "publicationYear": "2022",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/Dampak_Ekspansi_Biomassa_sebagai_Energi.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.69 MB",
    "contentPreview": "p-ISSN : 2528- 3561 \ne-ISSN : 2541- 1934 Volume VII, No.4, Oktobe r 2022 Hal 403 6 - 4050  \n4036   \n  \nDampak Ekspansi Biomassa s ebagai Ener gi Terbar ukan: \nKasus Ener gi Terbaruk an Indonesia  \n \nSyaifuddin Yana1*, Ne lly2, Radhiana3, Nasir Ibrahim4, Awal Afrizal Z ubir5, T.M. Zulfi kar6, \nArdhana Yu lisma7 \n \n1Program Studi Teknik Industri Fakulta s Teknik, Universita s Serambi Mekkah Banda A ceh Indones ia \n1,2,3,4Program Studi Mana jemen Universita s Serambi Mekkah Banda A ceh Indones ia \n"
  },
  {
    "id": "journal-c88214a45076",
    "filename": "energi terbarukan garuda1568782.pdf",
    "title": "energi terbarukan garuda1568782",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Abubakar Lubis et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/energi terbarukan garuda1568782.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.03 MB",
    "contentPreview": "156 Lubis, A. 2007ENERGI TERBARUKAN DALAM PEMBANGUNAN\nBERKELANJUTAN\nAbubakar Lubis\nPeneliti di Tekknologi Konversi dan Konservasi Energi,\nBadan Pengkajian dan Penerapan Teknologi\nAbstract\nRenewable energy is non fossil energy which can be renewed and managed properly.Therefore, the renewable energy resources would be sustainable. Those that can beclassified as renewable energy are geothermal, hydro, solar, wind, biomass, ocean,fuel cell, and nuclear.\nKeywords : renewable energy, sustainable\n1. P"
  },
  {
    "id": "journal-a0236d514577",
    "filename": "energies-13-05664.pdf",
    "title": "energies-13-05664",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Energy Consumption and Greenhouse Gas Emissions et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2020",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/energies-13-05664.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.25 MB",
    "contentPreview": "energies\nArticle\nEnergy Consumption and Greenhouse Gas Emissions\nof Nickel Products\nWenjing Wei1,2,*, Peter B. Samuelsson1\n, Anders Tilliander1, Rutger Gyllenram1,2and\nPär G. Jönsson1\n1Department of Materials Science and Engineering, Royal Institute of Technology, 114 28 Stockholm, Sweden;\npetersam@kth.se (P .B.S.); anderst@kth.se (A.T.); rutger.gyllenram@kobolde.com (R.G.); parj@kth.se (P .G.J.)\n2Kobolde &Partners AB, Ringvägen 100, 118 60 Stockholm, Sweden\n*Correspondence: wenjingw@kth.se\nRece"
  },
  {
    "id": "journal-8b532ae53f70",
    "filename": "ermm_indonesia_export_ban_of_nickel.pdf",
    "title": "ermm_indonesia_export_ban_of_nickel",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Export Restrictions on et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/ermm_indonesia_export_ban_of_nickel.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.67 MB",
    "contentPreview": "Office of Industry and Competitiveness Analysis   \nWorking Paper ICA -104  \n \n \n \n \nExport Restrictions on \nMinerals and Metals: \nIndonesia’s Export Ban of \nNickel   \nFebruary  2024 \nDavid Guberman  \nSamantha Schreiber  \nAnna Perry  \n  \n \n \n \nDisclaimer: Office of Industry and Competitiveness Analysis working papers are the result of the ongoing \nprofessional research of USITC staff and solely represent the opinions and professional research of \nindividual authors. These papers do not necessaril"
  },
  {
    "id": "journal-454dffc1bcfb",
    "filename": "eScholarship UC item 4xn6n3xf.pdf",
    "title": "eScholarship UC item 4xn6n3xf",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Recent Work et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/eScholarship UC item 4xn6n3xf.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.53 MB",
    "contentPreview": "UC Davis\nRecent Work\nTitle\nThe UC Davis Emerging Lithium Battery Test Project\nPermalink\nhttps://escholarship.org/uc/item/4xn6n3xf\nAuthors\nBurke, Andy\nMiller, Marshall\nPublication Date\n2009-07-01\n \nPeer reviewed\neScholarship.org Powered by the California Digital Library\nUniversity of California"
  },
  {
    "id": "journal-017bb31b25ad",
    "filename": "Faraday_Insights_18_FINAL.pdf",
    "title": "Faraday_Insights_18_FINAL",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Developments in Lithium-Ion Battery Cathodes et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2023",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/Faraday_Insights_18_FINAL.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "2.03 MB",
    "contentPreview": "Faraday Insights - Issue 18: September 2023\nDevelopments in Lithium-Ion Battery Cathodes\nJohn-Joseph Marie, Energy Storage Analyst, Faraday Institution  \nStephen Gifford, Chief Economist, Faraday Institution\nCommercial battery chemistries are rapidly evolving, driven by market demands, improved \ncathode materials and electrification of transport. Existing cathode chemistries such as lithium iron \nphosphate and lithium nickel manganese cobalt batteries continue to fulfil market requirements. \nHow"
  },
  {
    "id": "journal-bc5cc4eb3a13",
    "filename": "fceng-04-978842.pdf",
    "title": "fceng-04-978842",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Saeed Rahimpour Golroudbary, Andrzej Kraslawski, et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": "10.3389/fceng.2022.978842",
    "pdfUrl": "./data_jurnal/fceng-04-978842.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.76 MB",
    "contentPreview": "Assessment of environmental\nsustainability of nickel required for\nmobility transition\nSaeed Rahimpour Golroudbary1*, Andrzej Kraslawski2*,\nBenjamin P. Wilson1and Mari Lundström1\n1Department of Chemical and Metallurgical Engineering, Hydrometallurgy and Corrosion, Circular Raw\nMaterials Hub, Aalto University, Espoo, Finland,2School of Engineering Science, Industrial Engineering and\nManagement (IEM), LUT University, Lappeenranta, Finland\nNickel (Ni) in batteries (e.g., nickel-metal hydride battery"
  },
  {
    "id": "journal-b4df4bfa295d",
    "filename": "fenrg-08-594857.pdf",
    "title": "fenrg-08-594857",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "View of Raw Material Supply Shortfalls et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": "10.3389/fenrg.2020.594857",
    "pdfUrl": "./data_jurnal/fenrg-08-594857.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.24 MB",
    "contentPreview": "Tackling xEV Battery Chemistry in\nView of Raw Material Supply Shortfalls\nDuygu Karabelli1*, Steffen Kiemel1, Soumya Singh1, Jan Koller2, Simone Ehrenberger3,\nRobert Miehe1, Max Weeber1and Kai Peter Birke1,4\n1Fraunhofer Institute for Manufacturing Engineering and Automation IPA, Stuttgart, Germany,2Fraunhofer Institute for\nManufacturing Engineering and Automation IPA, Bayreuth, Germany,3Institute of Vehicle Concepts, German Aerospace Center\n(DLR), Stuttgart, Germany,4Institute for Photovoltaics, "
  },
  {
    "id": "journal-63a3cb814796",
    "filename": "Hati_2024_IOP_Conf._Ser.__Earth_Environ._Sci._1412_012026.pdf",
    "title": "Hati_2024_IOP_Conf._Ser.__Earth_Environ._Sci._1412_012026",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Earth and et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/Hati_2024_IOP_Conf._Ser.__Earth_Environ._Sci._1412_012026.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.79 MB",
    "contentPreview": "IOP Conference Series:\nEarth and\nEnvironmental Science\n      \nPAPER • OPEN ACCESS\nNickel ore export prohibition and mapping the\nbusiness performance of nickel mining companies\nin Indonesia\nTo cite this article: S N A P Hati et al 2024 IOP Conf. Ser.: Earth Environ. Sci.  1412 012026 \n \nView the article online  for updates and enhancements. You may also like \nStudy on Nickel Morphological Change at \nActive Three-Phase-Boundary in Solid \nOxide Fuel Cell Anode Using Patterned \nNickel-film Electrode"
  },
  {
    "id": "journal-27e5df5edc7e",
    "filename": "J-2.pdf",
    "title": "J-2",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "ISSN: XXXX -XXXX et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/J-2.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.52 MB",
    "contentPreview": " \n \nJournal of Sustainable Renewable Energy Innovations and \nPractices  \nISSN: XXXX -XXXX   \n \n  \n \n16 \n \nIntelligent Solar Energy Management through Human -Computer \nInteraction and Generative Adversarial Networks            \n \nLeena Tan Wei Ling1, Jason Ong Hwee2 \n1 School of Computer Science & Engineering,  National University of Singapore , Singapo re \n2Department of Artificial Intelligence , Nanyang Technological University , Singapore  \n \nAbstract:  \n \nThe management and optimization of so"
  },
  {
    "id": "journal-2d962c43c04f",
    "filename": "Kasyfilham_2025_IOP_Conf._Ser.__Earth_Environ._Sci._1537_012045.pdf",
    "title": "Kasyfilham_2025_IOP_Conf._Ser.__Earth_Environ._Sci._1537_012045",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Earth and et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/Kasyfilham_2025_IOP_Conf._Ser.__Earth_Environ._Sci._1537_012045.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.27 MB",
    "contentPreview": "IOP Conference Series:\nEarth and\nEnvironmental Science\n      \nPAPER • OPEN ACCESS\nFrom Spatial Potential to Extractive Reality: The\nPolitics of Nickel and Energy Transition in\nMorowali\nTo cite this article: Faiz Kasyfilham et al 2025 IOP Conf. Ser.: Earth Environ. Sci.  1537 012045 \n \nView the article online  for updates and enhancements. You may also like \nThe role of land in a just transition: the \nAppalachian Land Study collective \nLindsay Shade, Karen Rignall, Lyndsay \nTarus et al. -\nGendere"
  },
  {
    "id": "journal-9593da618843",
    "filename": "Mustafa_2023_IOP_Conf._Ser.__Earth_Environ._Sci._1151_012024.pdf",
    "title": "Mustafa_2023_IOP_Conf._Ser.__Earth_Environ._Sci._1151_012024",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Earth and et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/Mustafa_2023_IOP_Conf._Ser.__Earth_Environ._Sci._1151_012024.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.32 MB",
    "contentPreview": "IOP Conference Series:\nEarth and\nEnvironmental Science\n      \nPAPER • OPEN ACCESS\nGeochemical assesment of heavy metals in\npostmining laterite nickel, North Konawe\nSoutheast Sulawesi\nTo cite this article: M Mustafa et al 2023 IOP Conf. Ser.: Earth Environ. Sci.  1151 012024 \n \nView the article online  for updates and enhancements. You may also like \nCorrecting Exoplanet Transmission \nSpectra for Stellar Activity with an \nOptimized Retrieval Framework \nAlexandra Thompson, Alfredo Biagini, \nGianlu"
  },
  {
    "id": "journal-49d9e91c16e2",
    "filename": "NoorminshahAIahad2022_AIBasedChatbotsAdoptionModel.pdf",
    "title": "NoorminshahAIahad2022_AIBasedChatbotsAdoptionModel",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "N.; Yusof, A.F.; A. Al-Sharaﬁ, M. et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2022",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/NoorminshahAIahad2022_AIBasedChatbotsAdoptionModel.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.38 MB",
    "contentPreview": "Citation: Mohd Rahim, N.I.; A. Iahad,\nN.; Yusof, A.F.; A. Al-Sharaﬁ, M.\nAI-Based Chatbots Adoption Model\nfor Higher-Education Institutions: A\nHybrid PLS-SEM-Neural Network\nModelling Approach. Sustainability\n2022 ,14, 12726. https://doi.org/\n10.3390/su141912726\nAcademic Editors: Dolors Cañabate,\nJordi Colomer Feliu and\nRemigijus Bubnys\nReceived: 17 August 2022\nAccepted: 26 September 2022\nPublished: 6 October 2022\nPublisher’s Note: MDPI stays neutral\nwith regard to jurisdictional claims in\npublish"
  },
  {
    "id": "journal-14f15650a082",
    "filename": "on-evaluating-and-comparing-conversational-agents.pdf",
    "title": "on-evaluating-and-comparing-conversational-agents",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "{roprasad,chengmc,behnam,ametalli,goerahul,ranirudh}@amazon.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/on-evaluating-and-comparing-conversational-agents.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.20 MB",
    "contentPreview": "On Evaluating and Comparing Conversational\nAgents\nAnu Venkatesh,1Chandra Khatri,1Ashwin Ram,1Fenfei Guo\u0003,2\nRaefer Gabriel,1Ashish Nagar,1Rohit Prasad,1Ming Cheng,1\nBehnam Hedayatnia,1Angeliki Metallinou,1Rahul Goel,1Shaohua Yang,y3Anirudh Raju1\n1Amazon Alexa,2University of Maryland,3Michigan State University\n{anuvenk,ckhatri,ashwram,raeferg,nashish}@amazon.com\n{roprasad,chengmc,behnam,ametalli,goerahul,ranirudh}@amazon.com\nfenfeigo@cs.umd.edu ,yangshao@msu.edu\nAbstract\nConversational agents are "
  },
  {
    "id": "journal-14a59e0727e1",
    "filename": "out.pdf",
    "title": "out",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Indonesia’s nickel export ban et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2023",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/out.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.00 MB",
    "contentPreview": " \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \n \nIndustrial Policy in Indonesia: A quantitative analysis of \nIndonesia’s nickel export ban  \n \n \n \n \n \nSophie Baumgartner  \n \n \n \n \n \nMaster in Economics  \n \n \n \n \n \nSupervisor:  \nPhD João Silva, Assistant Professor, Iscte -Iul \n \n   \n \n \n \n \n \nOctober, 2023  "
  },
  {
    "id": "journal-4a26f2d86c05",
    "filename": "PIIS2405844022005928.pdf",
    "title": "PIIS2405844022005928",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Breaking barriers to low-carbon development in Indonesia: de",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/PIIS2405844022005928.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.78 MB",
    "contentPreview": "Research article\nBreaking barriers to low-carbon development in Indonesia: deployment of\nrenewable energy\nMaxensius Tri Sambodoa,b,*, Chitra Indah Yulianaa, Syarif Hidayata, Rio Novandraa,\nFelix Wisnu Handoyoa, Alan Ray Farandya, Ika Inayaha, Putri Irma Yuniartia\naResearcher at the Economic Research Center, Indonesian Institute of Sciences (LIPI) / National Research and Innovation Agency (BRIN), Indonesia\nbVisiting Researcher at Bank Indonesia Institute, Indonesia\nARTICLE INFO\nKeywords:\nLow-carb"
  },
  {
    "id": "journal-492a67964e8f",
    "filename": "PIIS2405844024037113.pdf",
    "title": "PIIS2405844024037113",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Available online March et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/PIIS2405844024037113.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "6.29 MB",
    "contentPreview": "Heliyon 10 (2024) e27680\nAvailable online 27 March 2024\n2405-8440/© 2024 The Author(s). Published by Elsevier Ltd. This is an open access article under the CC BY license\n(http://creativecommons.org/licenses/by/4.0/ ).Research article \nTechno-economic feasibility study of solar photovoltaic power \nplant using RETScreen to achieve Indonesia energy transition \nHendry Timotiyas Paradongana,*, Dzikri Firmansyah Hakama, \nSudarso Kaderi Wiryonoa, Iswan Prahastonob,c, Indra A. Adityab, \nKevin M. Banjarn"
  },
  {
    "id": "journal-8cc7d4d92159",
    "filename": "practical-pathways-to-higher-energy-density-lmfp-battery-cathodes.pdf",
    "title": "practical-pathways-to-higher-energy-density-lmfp-battery-cathodes",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "GerardBree,JingyiZhao,VeronikaMajherova, DanielaProprentner,",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/practical-pathways-to-higher-energy-density-lmfp-battery-cathodes.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "6.13 MB",
    "contentPreview": "PracticalPathwaystoHigherEnergyDensityLMFPBatteryCathodes\nPublishedasapartofEnergy &Fuelsspecialissue“2025PioneersinEnergyResearch:PrashantKamat”.\nGerardBree,*JingyiZhao,VeronikaMajherova, DanielaProprentner, GaloJ.PaezFajardo,\nandLouisF.J.Piper*\nCiteThis:EnergyFuels2025,39,3683−3689\n ReadOnline\nACCESS\n Metrics &More\n Article Recommendations +sıSupporting Information\nABSTRACT: Thedesignofnewlithium-ion batterycathode\nmaterialsmustbalancemanyfactors:performance, cost,manufactur-\nability,safety,cr"
  },
  {
    "id": "journal-da9f403f76f0",
    "filename": "REFORMING ENVIRONMENTAL GOVERNANCE  IN RESPONSE TO INDONESIA_S NICKEL INDUSTRIAL POLICY_ A CRITICAL ASSESSMENT OF SUSTAINABILITY CHALLENGES.pdf",
    "title": "REFORMING ENVIRONMENTAL GOVERNANCE  IN RESPONSE TO INDONESIA_S NICKEL INDUSTRIAL POLICY_ A CRITICAL ASSESSMENT OF SUSTAINABILITY CHALLENGES",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Univ ersity , et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": "10.7454/global.v27i1.1377",
    "pdfUrl": "./data_jurnal/REFORMING ENVIRONMENTAL GOVERNANCE  IN RESPONSE TO INDONESIA_S NICKEL INDUSTRIAL POLICY_ A CRITICAL ASSESSMENT OF SUSTAINABILITY CHALLENGES.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.37 MB",
    "contentPreview": "Global: Jurnal P olitik Internasional Global: Jurnal P olitik Internasional \nVolume 27 Number 1 Article 4 \n9-14-2025 \nREFORMING ENVIRONMEN TAL GO VERN ANCE IN RESPONSE T O REFORMING ENVIRONMEN TAL GO VERN ANCE IN RESPONSE T O \nINDONESI A’S NICKEL INDUSTRI AL POLICY: A CRI TICAL INDONESI A’S NICKEL INDUSTRI AL POLICY: A CRI TICAL \nASSESSMEN T OF SUST AINABILI TY CH ALLENGES ASSESSMEN T OF SUST AINABILI TY CH ALLENGES \nFarah Rosada \nDepar tment of International Relations, F aculty of Social and P "
  },
  {
    "id": "journal-32f1e42c13aa",
    "filename": "roskill-jrc_classi_ni_market_study_identifiers_final.pdf",
    "title": "roskill-jrc_classi_ni_market_study_identifiers_final",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Author Belum Terdeteksi (Perlu Review Manual)",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/roskill-jrc_classi_ni_market_study_identifiers_final.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "3.11 MB",
    "contentPreview": " \n \n \n \n \n \n \n \n \n \n \n \n \n \n \nStudy on future demand and \nsupply security of nickel  for \nelectric vehicle batteries  \n \n \n \nExternal study performed by  \n \nfor the Joint Research Centre  \n \n \n \n \n \n \n \n \n \n \n \n \n \n"
  },
  {
    "id": "journal-7f013019ca25",
    "filename": "s11027-019-09869-2.pdf",
    "title": "s11027-019-09869-2",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Jarod C. Kelly&Qiang Dai&Michael Wang et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2019",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/s11027-019-09869-2.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "2.58 MB",
    "contentPreview": "ORIGINAL ARTICLE\nGlobally regional life cycle analysis of automotive\nlithium-ion nickel manganese cobalt batteries\nJarod C. Kelly1&Qiang Dai1&Michael Wang1\nReceived: 17 April 2019 / Accepted: 13 May 2019 /\n#The Author(s) 2019, corrected Publication, May 2020\nAbstract\nElectric vehicles based on lithium-ion batteries (LIB) have seen rapid growth over the past decade\nas they are viewed as a cleaner alternative to convent ional fossil-fuel burning vehicles, especially\nfor local pollutant (nitrogen o"
  },
  {
    "id": "journal-33f4d5b474a2",
    "filename": "s12302-025-01159-w.pdf",
    "title": "s12302-025-01159-w",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Environmental Sciences Europe () : et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/s12302-025-01159-w.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.75 MB",
    "contentPreview": "Leal Filho  et al. \nEnvironmental Sciences Europe          (2025) 37:124  \nhttps://doi.org/10.1186/s12302-025-01159-w\nRESEARCH\nUsing artificial intelligence in sustainability \nteaching and learning\nWalter Leal Filho1,2  , Eundeok Kim3*  , Jaluza Maria Lima Silva Borsatto4   and Carla Bonato Marcolin4   \nAbstract \nBackground The integration of artificial intelligence (AI) in sustainability education (SE) represents a forward-\nthinking approach to teaching and learning, addressing complex global c"
  },
  {
    "id": "journal-428ddfb8a171",
    "filename": "s41467-024-54634-y.pdf",
    "title": "s41467-024-54634-y",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Carbon footprint distributions of lithium-ion et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/s41467-024-54634-y.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "2.47 MB",
    "contentPreview": "Article https://doi.org/10.1038/s41467-024-54634-y\nCarbon footprint distributions of lithium-ion\nbatteries and their materials\nLeopold Peiseler1,2,3, Vanessa Schenker4, Karin Schatzmann1,3,\nStephan P ﬁster3,4, Vanessa Wood2,3&T o b i a sS c h m i d t1,3\nLithium-ion batteries are pivotal in climate change mitigation. While their own\ncarbon footprint raises concerns, existing studies are scattered, hard tocompare and largely overlook the relev ance of battery materials. Here, we go\nbeyond traditio"
  },
  {
    "id": "journal-e422bca1b672",
    "filename": "s43246-020-00095-x.pdf",
    "title": "s43246-020-00095-x",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Future material demand for automotive et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2020",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/s43246-020-00095-x.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.81 MB",
    "contentPreview": "ARTICLE\nFuture material demand for automotive\nlithium-based batteries\nChengjian Xu1,3, Qiang Dai2, Linda Gaines2, Mingming Hu1, Arnold Tukker1& Bernhard Steubing1,3✉\nThe world is shifting to electric vehicles to mitigate climate change. Here, we quantify the\nfuture demand for key battery materials, considering potential electric vehicle ﬂeet and\nbattery chemistry developments as well as second-use and recycling of electric vehiclebatteries. We ﬁnd that in a lithium nickel cobalt manganese oxide "
  },
  {
    "id": "journal-18b2ee7441a9",
    "filename": "s44296-025-00059-7.pdf",
    "title": "s44296-025-00059-7",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Improving process granularity of life cycle et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/s44296-025-00059-7.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "2.15 MB",
    "contentPreview": "npj | materia lss u s t a i n a b i lity Article\nhttps://doi.org/10.1038/s44296-025-00059-7\nImproving process granularity of life cycle\ninventories for battery grade nickel\nCheck for updates\nSophia Roy1, Hossam Moustafa1, Ketan Vaidya2, Jean-Philippe Harvey1& Louis Fradette1\nBatteries are essential to transition to a fossil-free energy system, but only if coherently planned will their\nmanufacturing generate minimal environmental impacts. Aggregated life cycle inventories for battery-grade nickel"
  },
  {
    "id": "journal-794866af2e9d",
    "filename": "sustainability-17-02216.pdf",
    "title": "sustainability-17-02216",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Yongming Yao et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/sustainability-17-02216.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "3.06 MB",
    "contentPreview": "Academic Editors: Tianyu Li and\nYongming Yao\nReceived: 8 January 2025\nRevised: 3 February 2025\nAccepted: 14 February 2025\nPublished: 4 March 2025\nCitation: Aditya, I.A.; Wijayanto, T.;\nHakam, D.F. Advancing Renewable\nEnergy in Indonesia: A Comprehensive\nAnalysis of Challenges, Opportunities,\nand Strategic Solutions. Sustainability\n2025 ,17, 2216. https://doi.org/\n10.3390/su17052216\nCopyright: © 2025 by the authors.\nLicensee MDPI, Basel, Switzerland.\nThis article is an open access article\ndistrib"
  },
  {
    "id": "journal-0e939214645a",
    "filename": "Thesis_Draft_-_Raden_Dicky_Johar_Pribadi_FIN_REV.pdf",
    "title": "Thesis_Draft_-_Raden_Dicky_Johar_Pribadi_FIN_REV",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Prohibition for Indonesia in Consolidating et al.",
    "authorInstitution": "Not specified",
    "publicationYear": "2024",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/Thesis_Draft_-_Raden_Dicky_Johar_Pribadi_FIN_REV.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.74 MB",
    "contentPreview": "The Significance of the Nickel Ore Export \nProhibition for Indonesia in Consolidating   \nIts Middle -Income Status in the World System  \n \n \n \n \n \nRaden Dicky Johar Pribadi  \nSupervisor: Catarina Kinnvall  \nSIMZ -2024  \nSpring 2024  \n \n \n \nGraduate School  \nMaster of Science in Global Studies  \nDepartment of Political Science  \nLund Universit y\n"
  },
  {
    "id": "journal-ef0637bcbcd5",
    "filename": "UW-CSE-09-02-01.pdf",
    "title": "UW-CSE-09-02-01",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Promoting Energy Efficient Behaviors in the Home th rough",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/UW-CSE-09-02-01.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "0.51 MB",
    "contentPreview": "This paper was originally presented as a Boaster at  the HCIC 2009 Workshop and subsequently released as  a UW tech note #09-02-01. \n \nPromoting Energy Efficient Behaviors in the Home th rough \nFeedback: The Role of Human-Computer Interaction \nJon Froehlich  \nDUB Institute \nDepartment of Computer Science and Engineering \nUniversity of Washington, Seattle, WA 98195 USA \njfroehli@cs.washington.edu   \n \nAbstract \nThe consumption of energy is unlike most consumable  goods. It is abstract, invisible,"
  },
  {
    "id": "journal-d2d4c60bb155",
    "filename": "Vakulchuk-Indonesia-2020.pdf",
    "title": "Vakulchuk-Indonesia-2020",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "Indonesia: How to Boost Investment in Renewable Energy",
    "authorInstitution": "Not specified",
    "publicationYear": "2025",
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/Vakulchuk-Indonesia-2020.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.16 MB",
    "contentPreview": "Norwegian Institute of International Affairs (NUPI) \n \n \nIndonesia: How to Boost Investment in Renewable Energy \nAuthor(s): Roman Vakulchuk, Hoy-Yen Chan, Muhammad Rizki Kresnawan, Monika \nMerdekawati, Indra Overland, Haakon Fossum Sagbakken, Beni Suryadi, Nuki Agya Utama \nand  Zulfikar Yurnaidi \nNorwegian Institute of International Affairs (NUPI) (2020) \nStable URL: https://www.jstor.org/stable/resrep26573 \nAccessed: 02-12-2025 07:01 UTC \n \nJSTOR is a not-for-profit service that helps scholars,"
  },
  {
    "id": "journal-b1406b4ad3ac",
    "filename": "WP-LPEM-052-Unlocking_Renewable_Energy_Potential_in_Indonesia_Rev.pdf",
    "title": "WP-LPEM-052-Unlocking_Renewable_Energy_Potential_in_Indonesia_Rev",
    "uploader": "Kontributor (System)",
    "detectedAuthor": "UNL OCKING RENEW ABLE ENER GY et al.",
    "authorInstitution": "Not specified",
    "publicationYear": null,
    "journalSource": "Unknown",
    "doi": null,
    "pdfUrl": "./data_jurnal/WP-LPEM-052-Unlocking_Renewable_Energy_Potential_in_Indonesia_Rev.pdf",
    "uploadDate": "2025-12-10",
    "status": "pending",
    "fileSize": "1.31 MB",
    "contentPreview": "June 2020LPEM-FEB UI W orking P aper - 052 ISSN 2356-4008\nUNL OCKING RENEW ABLE ENER GY \nPOTENTIAL IN INDONESIA: \nASSESSMENT ON PR OJECT VIABILITY\nRafika Farah MauliaAtiqah Amanda Siregar"
  }
];

export default extractedMetadata;
